# Generated by Django 4.0.6 on 2022-12-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0003_post_fecha_alter_post_titulo_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='categoria',
            field=models.CharField(default='informacion', max_length=60),
        ),
    ]
