# Generated by Django 4.0.6 on 2022-12-09 23:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0005_delete_categoria_remove_post_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
    ]
