# Generated by Django 4.0.6 on 2022-12-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0006_alter_post_cuerpo_alter_post_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen_cabezera',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='descripcion',
            field=models.CharField(default='click en el link para leer mas', max_length=100),
        ),
    ]
