# Generated by Django 4.0.6 on 2022-12-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0008_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='Instagram_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='Twitter_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='fb_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='github_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='perfil_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/perfil/'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='web_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
